;;; check-package.el -*- lexical-binding: t; no-byte-compile: t; -*-
(require 'cl-lib)
(require 'package)
(require 'use-package)

(let* ((repository (or (getenv "NEO_TERM_PACKAGE_URL")
                       (expand-file-name ".." (file-name-directory load-file-name))))
       (directory (make-temp-file "neo-term-package-" t))
       (user-emacs-directory (file-name-as-directory directory))
       (package-user-dir (expand-file-name "elpa" directory))
       (package-archives nil))
  (unwind-protect
      (progn
        (package-initialize)
        (eval `(use-package neo-term
                 :vc (:url ,repository :rev :newest :vc-backend Git)
                 :commands neo-term))
        (cl-assert (package-installed-p 'neo-term))
        (cl-assert (autoloadp (symbol-function 'neo-term)))
        (require 'neo-term)
        (cl-assert (file-in-directory-p neo-term-module-program package-user-dir))
        (cl-assert (file-exists-p neo-term-module-program))
        (let* ((neo-term-shell "cmd.exe")
               (neo-term-shell-arguments '("/Q"))
               (buffer (neo-term)))
          (unwind-protect
              (with-current-buffer buffer
                (let ((deadline (+ (float-time) 10)))
                  (while (and (not neo-term--session) (< (float-time) deadline))
                    (accept-process-output nil .05))
                  (cl-assert neo-term--session))
                (cl-assert (equal (alist-get 'backend neo-term--session) "system-conpty"))
                (neo-term--send "Techo NEO^_PACKAGE_OK")
                (neo-term--send "K1,0")
                (let ((deadline (+ (float-time) 10)))
                  (while (and (not (string-match-p "NEO_PACKAGE_OK" (buffer-string)))
                              (< (float-time) deadline))
                    (accept-process-output nil .05))
                  (cl-assert (string-match-p "NEO_PACKAGE_OK" (buffer-string)))))
            (when (buffer-live-p buffer) (kill-buffer buffer))))
        (princ "NEO_TERM_PACKAGE=PASS\n"))
    (when (and (file-in-directory-p directory temporary-file-directory)
               (string-prefix-p "neo-term-package-" (file-name-nondirectory directory)))
      (delete-directory directory t))))
