"""Regenerate terminal widths from checked-in official Unicode 16.0.0 data.

Source: https://www.unicode.org/Public/16.0.0/ucd/
Data terms: native/unicode-data/LICENSE.txt (Unicode License V3).
Run from any directory: python tools/generate-unicode.py [--check]
"""
import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "native" / "unicode-data"
OUTPUT = ROOT / "native" / "unicode-width.hpp"


def intervals(points):
    result = []
    for point in sorted(points):
        if result and point == result[-1][1] + 1:
            result[-1][1] = point
        else:
            result.append([point, point])
    return result


def generate():
    zero = set(range(0x1160, 0x1200))
    start = None
    for line in (DATA / "UnicodeData.txt").read_text(encoding="utf-8").splitlines():
        fields = line.split(";")
        point, name, category = int(fields[0], 16), fields[1], fields[2]
        if name.endswith(", First>"):
            start = point
        elif name.endswith(", Last>"):
            if category in {"Mn", "Me", "Cf"}:
                zero.update(range(start, point + 1))
            start = None
        elif category in {"Mn", "Me", "Cf"}:
            zero.add(point)
    zero.discard(0xAD)  # Soft hyphen occupies a terminal cell.
    wide = set()
    for line in (DATA / "EastAsianWidth.txt").read_text(encoding="utf-8").splitlines():
        record = line.split("#", 1)[0].strip()
        if not record:
            continue
        extent, width = (part.strip() for part in record.split(";"))
        if width not in {"W", "F"}:
            continue
        bounds = [int(part, 16) for part in extent.split("..")]
        wide.update(range(bounds[0], bounds[-1] + 1))
    wide.difference_update(zero)
    result = ["// Generated by tools/generate-unicode.py; do not edit.",
              "// Official Unicode 16.0.0 data; see unicode-data/LICENSE.txt."]
    for name in ("UnicodeData.txt", "EastAsianWidth.txt"):
        digest = hashlib.sha256((DATA / name).read_bytes()).hexdigest()
        result.append(f"// {name} SHA-256: {digest}")
    result.extend(["#pragma once", "#include <cstddef>", "#include <cstdint>",
                   "", "namespace neo {", "namespace unicode_detail {",
                   "struct Interval { uint32_t first, last; };"])
    for name, points in (("zero_width", zero), ("double_width", wide)):
        result.append(f"inline constexpr Interval {name}[] = {{")
        result.extend(f"    {{0x{first:X}, 0x{last:X}}}," for first, last in intervals(points))
        result.append("};")
    result.extend(["", "template <std::size_t N>",
                   "inline bool contains(const Interval (&ranges)[N], uint32_t point) {",
                   "    std::size_t first = 0, last = N;",
                   "    while (first < last) {",
                   "        const auto middle = first + (last - first) / 2;",
                   "        if (point < ranges[middle].first) last = middle;",
                   "        else if (point > ranges[middle].last) first = middle + 1;",
                   "        else return true;", "    }", "    return false;", "}",
                   "} // namespace unicode_detail", "",
                   "// Controls are interpreted by the terminal parser, not this width policy.",
                   "inline int unicode_width(uint32_t point) {",
                   "    if (unicode_detail::contains(unicode_detail::zero_width, point)) return 0;",
                   "    if (unicode_detail::contains(unicode_detail::double_width, point)) return 2;",
                   "    return 1;", "}", "} // namespace neo", ""])
    return "\n".join(result)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if checked-in output is stale")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("unicode-width.hpp is stale; run tools/generate-unicode.py")
        print("Unicode 16.0.0 width tables match official source data")
    else:
        OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
